# Site settings
title: Your awesome title
email: mahmut_surekci@live.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Just a platform to share my findings for software development in general.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  msurekci

# Build settings
markdown: kramdown
